apiVersion: v1
kind: Service
metadata:
  name: node-deploy-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31704
    port: 3000
    targetPort: 3000
  selector:
    app: awsgovrg