---
- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      become: yes
      become_user: vagrant
      shell: sudo kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "sudo {{ join_command_raw.stdout_lines[0] }}"


- hosts: worker
  become: yes
  tasks:
    - name: disable swap memory
      shell: swapoff -a

    - name: join cluster
      become: yes
      become_user: vagrant
      shell: "{{ hostvars['master1'].join_command }}"
